import { sample } from 'lodash';
import { faker} from '@faker-js/faker';

// ----------------------------------------------------------------------

const types = ['Clothes', 'Toys', 'Food', 'Medical Suplies', 'School Supplies', 'Blood Donations'];
const itemTypeList = {
    'Clothes': [
        {age: 10,
         gender: "Male",
         season: "Winter",
         material: "Fabric",
         quantity: 3,
         subtype: "Shirt",
         },
         {age: 13,
         gender: "Male",
         season: "Fall",
         material: "Fabric",
         quantity: 6,
         subtype: "Shoes",
         },
         {age: 12,
         gender: "Female",
         season: "Fall",
         material: "Cotton",
         quantity: 1,
         subtype: "Trouser",
         },
         {age: 19,
         gender: "Female",
         season: "Winter",
         material: "Fabric",
         quantity: 10,
         subtype: "Shoes",
         },
         {age: 19,
         gender: "Male",
         season: "Fall",
         material: "Cotton",
         quantity: 10,
         subtype: "Trouser",
         },
         {age: 15,
         gender: "Female",
         season: "Spring",
         material: "Polyester",
         quantity: 10,
         subtype: "Shoes",
         },
         {age: 7,
         gender: "Male",
         season: "Winter",
         material: "Polyester",
         quantity: 7,
         subtype: "Shoes",
         },
         {age: 7,
         gender: "Male",
         season: "Spring",
         material: "Cotton",
         quantity: 9,
         subtype: "Dress",
         },
         {age: 15,
         gender: "Female",
         season: "Winter",
         material: "Cotton",
         quantity: 2,
         subtype: "Shirt",
         },
         {age: 19,
         gender: "Male",
         season: "Summer",
         material: "Polyester",
         quantity: 8,
         subtype: "Trouser",
         },
         {age: 6,
         gender: "Male",
         season: "Winter",
         material: "Cotton",
         quantity: 8,
         subtype: "Shirt",
         },
         {age: 16,
         gender: "Male",
         season: "Summer",
         material: "Cotton",
         quantity: 1,
         subtype: "Dress",
         },
         {age: 14,
         gender: "Female",
         season: "Spring",
         material: "Cotton",
         quantity: 2,
         subtype: "Dress",
         },
         {age: 19,
         gender: "Female",
         season: "Fall",
         material: "Fabric",
         quantity: 6,
         subtype: "Trouser",
         },
         {age: 12,
         gender: "Male",
         season: "Summer",
         material: "Cotton",
         quantity: 3,
         subtype: "Dress",
         },
         {age: 20,
         gender: "Female",
         season: "Winter",
         material: "Fabric",
         quantity: 4,
         subtype: "Dress",
         },
         {age: 11,
         gender: "Female",
         season: "Spring",
         material: "Polyester",
         quantity: 9,
         subtype: "Shirt",
         },
         {age: 7,
         gender: "Male",
         season: "Winter",
         material: "Polyester",
         quantity: 2,
         subtype: "Trouser",
         },
         {age: 11,
         gender: "Female",
         season: "Summer",
         material: "Polyester",
         quantity: 10,
         subtype: "Shoes",
         },
         {age: 12,
         gender: "Male",
         season: "Winter",
         material: "Cotton",
         quantity: 10,
         subtype: "Shirt",
         },],

    'School Supplies': [
        {type: "Stationary",
        subtype: "eraser",
        quantity: 9,
        },
        {type: "Stationary",
        subtype: "pen",
        quantity: 8,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 3,
        },
        {type: "Stationary",
        subtype: "pen",
        quantity: 7,
        },
        {type: "Stationary",
        subtype: "pencil case",
        quantity: 9,
        },
        {type: "Stationary",
        subtype: "pencil case",
        quantity: 7,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 8,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 4,
        },
        {type: "Stationary",
        subtype: "eraser",
        quantity: 8,
        },
        {type: "Stationary",
        subtype: "copy book",
        quantity: 5,
        },
        {type: "Stationary",
        subtype: "pencil",
        quantity: 10,
        },
        {type: "Stationary",
        subtype: "sharpner",
        quantity: 4,
        },
        {type: "Stationary",
        subtype: "pencil case",
        quantity: 5,
        },
        {type: "Stationary",
        subtype: "pencil",
        quantity: 4,
        },
        {type: "Stationary",
        subtype: "eraser",
        quantity: 6,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 3,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 9,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 8,
        },
        {type: "Stationary",
        subtype: "pencil",
        quantity: 1,
        },
        {type: "Book",
        bookName: "Physics of The Future",
        author: "Serway",
        language: "English",
        edition: "second",
        shortSummary: "A non-fiction book addressing how physics will affect the future of mankind",
        quantity: 9,
        },
    
    ],

    'Food': [
        {itemName: "eggs",
        quantity: 9,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 28,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 9,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 28,
        subtype: "baked goods",
        },
        {itemName: "eggs",
        quantity: 28,
        subtype: "baked goods",
        },
        {itemName: "eggs",
        quantity: 8,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 22,
        subtype: "baked goods",
        },
        {itemName: "eggs",
        quantity: 13,
        subtype: "canned foods",
        },
        {itemName: "eggs",
        quantity: 18,
        subtype: "baked goods",
        },
        {itemName: "eggs",
        quantity: 13,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 21,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 25,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 7,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 35,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 21,
        subtype: "canned foods",
        },
        {itemName: "eggs",
        quantity: 11,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 7,
        subtype: "canned foods",
        },
        {itemName: "eggs",
        quantity: 19,
        subtype: "fresh meals",
        },
        {itemName: "eggs",
        quantity: 11,
        subtype: "fruits and vegetables",
        },
        {itemName: "eggs",
        quantity: 16,
        subtype: "fresh meals",
        },
    ],

    'Toys':  [
        {age: 15,
            gender: "Female",
            subtype: "sports",
            type: "Car",
            quantity: 3,
            },
            {age: 15,
            gender: "Female",
            subtype: "dolls",
            type: "Car",
            quantity: 1,
            },
            {age: 7,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 7,
            },
            {age: 11,
            gender: "Female",
            subtype: "stuffed toys",
            type: "Car",
            quantity: 6,
            },
            {age: 13,
            gender: "Male",
            subtype: "sports",
            type: "Car",
            quantity: 6,
            },
            {age: 18,
            gender: "Female",
            subtype: "board games",
            type: "Car",
            quantity: 7,
            },
            {age: 8,
            gender: "Male",
            subtype: "stuffed toys",
            type: "Car",
            quantity: 10,
            },
            {age: 14,
            gender: "Male",
            subtype: "sports",
            type: "Car",
            quantity: 9,
            },
            {age: 14,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 3,
            },
            {age: 19,
            gender: "Female",
            subtype: "stuffed toys",
            type: "Car",
            quantity: 6,
            },
            {age: 8,
            gender: "Female",
            subtype: "board games",
            type: "Car",
            quantity: 10,
            },
            {age: 20,
            gender: "Male",
            subtype: "stuffed toys",
            type: "Car",
            quantity: 2,
            },
            {age: 13,
            gender: "Male",
            subtype: "sports",
            type: "Car",
            quantity: 2,
            },
            {age: 8,
            gender: "Male",
            subtype: "board games",
            type: "Car",
            quantity: 10,
            },
            {age: 9,
            gender: "Female",
            subtype: "stuffed toys",
            type: "Car",
            quantity: 8,
            },
            {age: 17,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 1,
            },
            {age: 14,
            gender: "Female",
            subtype: "board games",
            type: "Car",
            quantity: 1,
            },
            {age: 9,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 6,
            },
            {age: 18,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 2,
            },
            {age: 20,
            gender: "Male",
            subtype: "cars",
            type: "Car",
            quantity: 4,
            },
    ],

    'Medical Suplies': [
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 6,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 1,
        },
        {type: "Medication",
        medicalUse: "Mental Illness",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 10,
        },
        {type: "Medical Devices",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 8,
        },
        {type: "Medication",
        medicalUse: "Anti Biotic",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 6,
        },
        {type: "Medical Devices",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 4,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 6,
        },
        {type: "Medication",
        medicalUse: "Anti Biotic",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 6,
        },
        {type: "Medication",
        medicalUse: "Flu",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 8,
        },
        {type: "Medication",
        medicalUse: "Bacterial Infection",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 3,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 4,
        },
        {type: "Medical Devices",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 7,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 1,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 5,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 4,
        },
        {type: "Medical Equipment",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 1,
        },
        {type: "Medication",
        medicalUse: "Anti Biotic",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 5,
        },
        {type: "Medical Devices",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 6,
        },
        {type: "Medical Devices",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 4,
        },
        {type: "Medication",
        medicalUse: "Anti Biotic",
        deviceType: "Imaging",
        use: "surgery",
        quantity: 7,
        },
    ],

    'Blood Donations': [
        {hospitalName: "Orman",
        governorate: "Suez",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Cairo",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Suez",
        area: "area4",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Orman",
        governorate: "Giza",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Cairo",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Qasr",
        governorate: "Alexandria",
        area: "area3",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "57357",
        governorate: "Alexandria",
        area: "area1",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Orman",
        governorate: "Suez",
        area: "area4",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Orman",
        governorate: "Cairo",
        area: "area1",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Suez",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "57357",
        governorate: "Giza",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Qasr",
        governorate: "Giza",
        area: "area1",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Orman",
        governorate: "Alexandria",
        area: "area4",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "57357",
        governorate: "Giza",
        area: "area1",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Qasr",
        governorate: "Giza",
        area: "area1",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Giza",
        area: "area3",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Orman",
        governorate: "Suez",
        area: "area3",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Qasr",
        governorate: "Giza",
        area: "area4",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "GUC",
        governorate: "Suez",
        area: "area2",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
        {hospitalName: "Qasr",
        governorate: "Giza",
        area: "area3",
        hospitalAddress: "123 Main Street",
        patientName: "Roberto Fermino",
        bloodType: "A+",
        },
    ]       
}


export const items = [...Array(16)].map((_, index) => {
    const idx = Math.floor(Math.random() * types.length);
    return {
    generalType: types[idx],
    id: faker.string.uuid(),
    orgName: faker.company.name(),
    day: faker.number.int({min: 1 , max: 30}),
    month: faker.number.int({min: 1 , max: 12}),
    year: faker.number.int({min: 2018 , max: 2023}),
    type: types[idx],
    details: itemTypeList[types[idx]][Math.floor(Math.random() * 20)]
    }
});

export const items2 = [
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    },
    {patientName: "Roberto Fermino",
        age: 15,
        gender: 'Male',
        weight: 70,
        organizationName: 'Orman Hospital',
        speciality: 'sugery',
        decription: 'needs heart surgery as quickly as possible' 
    }
]

export const items3 = [
    {
    numberStudents: '5',
    address: '3rd district, 5th settlement, Cairo',
    subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
     },
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    }
    {
        numberStudents: '5',
        address: '3rd district, 5th settlement, Cairo',
        subject: 'Math'
    }
]


